Test
DrSergei/FA pull request #1
Opened 2022-09-20 14:03 UTC by DrSergei

2022-09-22 05:07 UTC, DrSergei commented
@katyacyfra

2022-09-26 19:19 UTC, katyacyfra approved these changes
Ок

2022-09-26 19:42 UTC, katyacyfra requested changes

2022-09-26 19:42 UTC, katyacyfra commented on src/main/kotlin/Main.kt
> +    override fun toString(): String {
что делает этот метод? Судя по тесту, он преобразовывает в DFA. Если это так, название абсолютно неподходящее

2022-09-26 19:42 UTC, katyacyfra commented on src/main/kotlin/Main.kt
> +fun main() {
Где инструкция для домохозяек (и не только) о том, какие параметры подавать на вход, что ожидать на выходе? Если я хочу запустить конвертацию в DFA, как мне это сделать?

2022-10-02 15:46 UTC, katyacyfra approved these changes
Ок

2022-10-02 16:49 UTC, merged